Major revamp
julian-alarcon/prospect-mail pull request #183
Opened 2021-09-26 20:01 UTC by joax

Major Revamp to the Version

 * Javascript injection into separate file
 * Fixed unread notifications (div changed)
 * Moved notifications to Electron notifications from HTML5
 * Fixed issue with Configuration flags (always true)
 * Configuration changes write to Configuration File
 * Added Frameless Mode (and config on Tray Menu)
 * Frameless Mode: Added Grab areas
 * Frameless Mode: Added close button to child windows
 * TO-DO on child window rather than browser

Tested on Ubuntu 20.04 LTS. Needs testing on MacOS and Windows.

**Needs version bump**

2021-09-26 20:03 UTC, joax commented on src/controller/mail-window-controller.js
> +            let that = this
This needs some love. Old ways must be cleaned on future release.

2021-09-26 20:04 UTC, joax commented on src/controller/mail-window-controller.js
> +                let that = this
Old ways to be cleaned.

2021-12-11 17:10 UTC, joax commented
I have been using this PR for quite a while now and it works very well, some of the features are much needed (adding close buttons to the windows created on border-less mode). I can retract the PR if that cleans the repo, lmk.

2021-12-11 22:43 UTC, julian-alarcon commented
I merged a PR to add missing spellcheck functionality, but it seems to be in conflict, can you review it? The changes was not so big @joax

2021-12-11 23:10 UTC, julian-alarcon requested changes
Also:
* I'm not sure if one intention of this PR is to provide this feature https://github.com/julian-alarcon/prospect-mail/issues/29 , I tested it and it didn't worked, notifications are still inside the window, not in the OS level. Could it be that something that is missing?
* I check your change to add deeplink for the ToDo, but it seems to still not opening a new Window.
* The unread  seems to be still broken, I see 3 dots instead of the tray icon. Can you show me an screenshot of how it looks at your end? (I'm using Ubuntu 20.04)

BTW Frameless feature work as intended!

2021-12-13 15:12 UTC, joax commented
Merged. Detected one issue when borderless mode, the auxiliary windows open with border/window title.

2022-03-29 13:25 UTC, andrea-nisti commented
Hello, notifications at OS level is a very appreciated feature. Any news about that? Thanks and awesome work!

2023-07-24 14:09 UTC, julian-alarcon submitted a review, later dismissed

2023-07-24 14:11 UTC, closed without merging